# Generated by Django 3.2.5 on 2021-11-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('computername', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('is_win7', models.BooleanField(default=False)),
                ('is_winxp', models.BooleanField(default=False)),
                ('is_win8', models.BooleanField(default=False)),
                ('is_win10', models.BooleanField(default=False)),
                ('is_win11', models.BooleanField(default=False)),
                ('is_x64', models.BooleanField(default=False)),
                ('is_server', models.BooleanField(default=False)),
            ],
        ),
    ]
