# Generated by Django 3.2.5 on 2021-11-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
