# Generated by Django 3.2.5 on 2021-11-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_bot_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='comment',
        ),
        migrations.AddField(
            model_name='bot',
            name='ip',
            field=models.CharField(default='', max_length=100),
        ),
    ]
