# Generated by Django 3.2.5 on 2021-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20211104_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
