# Generated by Django 3.2.5 on 2021-11-13 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_bot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='c',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='bot',
            name='date_ch',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
