# Generated by Django 3.2.5 on 2021-11-13 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_auto_20211113_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'ordering': ['-date']},
        ),
    ]
