# Generated by Django 3.2.5 on 2021-11-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='date_ch',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
