# Generated by Django 3.2.5 on 2021-11-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_auto_20211117_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='country',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
