# Generated by Django 3.2.5 on 2021-11-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_bot_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
