# Generated by Django 3.2.5 on 2021-11-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_bot_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=20)),
                ('_type', models.CharField(max_length=20)),
                ('win_os', models.CharField(max_length=100)),
                ('x_oc', models.CharField(max_length=50)),
            ],
        ),
    ]
