# Generated by Django 3.2.5 on 2021-11-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='repetitions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
