# Generated by Django 3.2.5 on 2021-11-25 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_auto_20211124_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='tasks',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admin_panel.task'),
        ),
    ]
