# Generated by Django 3.2.5 on 2021-11-25 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_alter_bot_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='bots',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.bot'),
        ),
    ]
