# Generated by Django 3.2.5 on 2021-11-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_auto_20211125_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bots',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.bot'),
        ),
    ]
