# Generated by Django 3.2.5 on 2021-11-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_alter_task_bots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='bots',
        ),
        migrations.AddField(
            model_name='bot',
            name='tasks',
            field=models.ManyToManyField(to='admin_panel.Task'),
        ),
    ]
