# Generated by Django 3.2.5 on 2021-11-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date']},
        ),
    ]
