# Generated by Django 3.2.5 on 2021-12-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_task_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBackConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=50)),
            ],
        ),
    ]
