# Generated by Django 3.2.5 on 2021-12-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_task_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='is_server2016_19',
            field=models.BooleanField(default=False),
        ),
    ]
