# Generated by Django 3.2.5 on 2021-12-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_bot_is_server2016_19'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='x_oc',
            field=models.CharField(default='', max_length=10),
        ),
    ]
