# Generated by Django 3.2.5 on 2021-12-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_bot_x_oc'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='type1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
